title: FFBRAIN Workshop
description: FFBRAIN Workshop at ECCV 2024
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
workshop:
  name: "Towards Multimodal Foundational Models for Brain Modelling"
  short: FFBRAIN
  host: "ECCV 2024<br>Milan, Italy<br>Sep 29 - Oct 4, 2024"
  submission_link: TBD
  dates:
    submission: July 15, 2024
    decision: August 10, 2024
    camera_ready: August 20, 2024
    workshop: September 30, 2024
  organizers:
    - name: Concetto 
      surname: Spampinato 
      affiliation: University of Catania
      email: concetto.spampinato@unict.it
      pic: img/concetto.jpg
    - name: Nouria Lakhdar
      surname: Ghazal 
      affiliation: Mohammed V University of Rabat
      email: 
      pic: img/pic.jpg
    - name: Andrea
      surname: Tolias 
      affiliation: University of Houston
      email: 
      pic: img/pic.jpg
    - name: Jonathan 
      surname: Xu 
      affiliation: University of Waterloo
      email: 
      pic: img/pic.jpg
    - name: Shanmuganathan 
      surname: Raman 
      affiliation: Indian Institute of Technology
      email: 
      pic: img/pic.jpg
    - name: Federica
      surname: Proietto Salanitri
      affiliation: University of Catania
      email: federica.proiettosalanitri@unict.it
      pic: img/federica.jpg
    - name: Matteo
      surname: Pennisi
      affiliation: Campus Bio Medico Rome
      email: 
      pic: img/pic.jpg
  pc:
  talks:
    - name: "TBA"
      affiliation: "TBA"
      pic: img/pic.jpg
      title: "TBD"
      file_text: "PDF"
      file_url: 
  program:
    
